language: node_js
node_js:
- "8"
script:
- yarn install
- yarn test
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: T1qzP66yzXw0XnCTDdVfAgTu02wy8/mzxgOK0CPjV80f78RWjxjfUshmv5lN4Z74R0sg1iQSQH/7JGyeLto8Zj47sHBMII1JlyG/jlamAJVlUe0jSbWH5n4im3jtLRT5edSP9crURUxf2lww5CT9t2aZM7En951uXf1DTv4tZm79VJemT20fl+VMEzPcMYMltSpy9gOLN83je+sDvTkVx0/C1VYI9209bFHfvXjdIODMsCCSJY+b4G/KwtcHxbpBeYw95b5kf1RjhXndGIZuDo0nQpTnplC6PJpERpSHtClkYgcROwvVHLza8CldoVqzqVTOts+qC+NYSVnVLhLyWeJzBHiWkQ5SrUKwNhcZev2YolA+bdjSYDNV3rXFkHt43cxHDHgjxKKz45VZMOK8xr+aJ7rUeGWojMsMziGQ9pCvGpfUgTU3RVbEqaBega6HfCguVIZJRCg/kIwiZHTxLTjQ9O6RAziJ8rIak/X+dBHuPz/XSZY+M6tR9tLiUKIp3ojsTfai99rej7q1BC6VWg9l3uOxsjUmdznRqX+d2UM+H/mSWe1JbL9I8nuEP9NR0B5KEVlZjw3ofQIfgL0TLst2NuSt0btt5KS++AZfQWczdOcrWE3HF5gsblbXFcEy56nqvofs2TUclRBaqrHvO7wmHLyBT1o+9PCKl0rSqGU=
  app: wurf-business
  on:
    repo: chenaicirt/wurf-business
